import { create } from "zustand";
import type { UserProfile } from "../types/travel";
import { authService } from "../services/supabase/auth";
import { dbService } from "../services/supabase/database";

interface AuthState {
  user: UserProfile | null;
  loading: boolean;
  error: string | null;
  initialized: boolean;
  isGuest: boolean;
  initialize: () => Promise<void>;
  signOut: () => Promise<void>;
  setGuestUser: () => void;
  clearError: () => void;
}

export const useAuthStore = create<AuthState>((set, get) => ({
  user: null,
  loading: false,
  error: null,
  initialized: false,
  isGuest: false,

  async initialize() {
    if (get().initialized) return;
    set({ loading: true });
    
    // Check if guest user session is in localStorage
    const savedGuest = localStorage.getItem("aria_guest_session");
    if (savedGuest) {
      try {
        const parsed = JSON.parse(savedGuest);
        set({ user: parsed, isGuest: true, initialized: true, loading: false });
        return;
      } catch (e) {
        localStorage.removeItem("aria_guest_session");
      }
    }

    try {
      const session = await authService.getSession();
      if (session?.user) {
        const profile = await dbService.getUserProfile(session.user.id);
        if (profile) {
          set({ user: profile, isGuest: false });
        } else {
          // Fallback if public profile isn't instantly generated by trigger
          set({
            user: {
              uid: session.user.id,
              email: session.user.email || "",
              displayName: session.user.user_metadata?.full_name || "",
              photoURL: session.user.user_metadata?.avatar_url,
              preferences: {
                styles: [],
                food: [],
                accommodation: [],
                currency: "USD",
                maxDailyBudget: 500,
              },
              isPro: false,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            isGuest: false,
          });
        }
      }
      // Set listener for auth state changes
      authService.onAuthStateChange(async (event, session) => {
        if (session?.user) {
          const profile = await dbService.getUserProfile(session.user.id);
          set({
            user: profile || {
              uid: session.user.id,
              email: session.user.email || "",
              displayName: session.user.user_metadata?.full_name || "",
              photoURL: session.user.user_metadata?.avatar_url,
              preferences: {
                styles: [],
                food: [],
                accommodation: [],
                currency: "USD",
                maxDailyBudget: 500,
              },
              isPro: false,
              createdAt: new Date().toISOString(),
              updatedAt: new Date().toISOString(),
            },
            isGuest: false,
          });
        } else {
          // Don't override guest session if we sign out of a null session
          if (!get().isGuest) {
            set({ user: null });
          }
        }
      });
      set({ initialized: true });
    } catch (err: any) {
      set({ error: err.message || "Failed to initialize authentication." });
    } finally {
      set({ loading: false });
    }
  },

  setGuestUser() {
    const guestProfile: UserProfile = {
      uid: "00000000-0000-0000-0000-000000000000",
      email: "guest@aria.ai",
      displayName: "Explorer Guest",
      preferences: {
        styles: [],
        food: [],
        accommodation: [],
        currency: "USD",
        maxDailyBudget: 500,
      },
      isPro: false,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    };
    localStorage.setItem("aria_guest_session", JSON.stringify(guestProfile));
    set({ user: guestProfile, isGuest: true, initialized: true });
  },

  async signOut() {
    set({ loading: true });
    try {
      if (get().isGuest) {
        localStorage.removeItem("aria_guest_session");
        set({ user: null, isGuest: false });
      } else {
        await authService.signOut();
        set({ user: null });
      }
    } catch (err: any) {
      set({ error: err.message || "Sign out failed." });
    } finally {
      set({ loading: false });
    }
  },

  clearError() {
    set({ error: null });
  },
}));
